In [1]:
import numpy as np

In [32]:
n=int(input("enter the dimension of the square matrices to be constructed..."))

In [34]:
a=[]
for i in range(0,n):
    l=[]
    for j in range(0,n):
        l.append(int(input("enter next element...")))
    a.append(l)

print(np.matrix((a)))


[[1 2]
 [3 4]]


In [35]:
b=[]
for i in range(0,n):
    l=[]
    for j in range(0,n):
        l.append(int(input("enter next element...")))
    b.append(l)

print(np.matrix((b)))


[[2 3]
 [4 5]]


In [36]:
print(np.dot(a,b))

[[10 13]
 [22 29]]


In [37]:
print(np.transpose(a))

[[1 3]
 [2 4]]


In [38]:
print(np.transpose(b))

[[2 4]
 [3 5]]


In [39]:
print(np.trace(a))

5


In [40]:
print(np.trace(b))

7


In [42]:
print(np.linalg.matrix_rank(a))

2


In [43]:
print(np.linalg.matrix_rank(b))

2


In [44]:
print(np.linalg.matrix_rank(a,b))

[[1 1]
 [1 1]]


In [45]:
print(np.linalg.det(a))

-2.0000000000000004


In [46]:
print(np.linalg.det(b))

-2.0


In [48]:
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [49]:
print(np.linalg.inv(b))

[[-2.5  1.5]
 [ 2.  -1. ]]


In [51]:
print(np.linalg.eigvals(a))

[-0.37228132  5.37228132]


In [53]:
vals,vectors=np.linalg.eig(b)

In [56]:
print("values  \n",vals)
print("vectors  \n",vectors)

values  
 [-0.27491722  7.27491722]
vectors  
 [[-0.79681209 -0.49436913]
 [ 0.60422718 -0.86925207]]
