In [1]:
import numpy as np

In [2]:
arr1=np.arange(20)

In [3]:
print(arr1)
arr1[(arr1>=9) & (arr1<=15)]*=-1
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [7]:
print(np.diag(np.arange(0,6)))


[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


ValueError: Input must be 1- or 2-d.

In [9]:
arr3=arr2=np.matrix((arr3,arr3))
print(arr2)

[[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
   18  19]
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
   18  19]]


In [13]:
print(np.diag(arr2))

[0 1]


In [15]:
a=np.array([1,2,3,4,5])
b=np.array([1,0,3,6,5])

In [16]:
c=np.matrix((a,b))

In [17]:
print(c)

[[1 2 3 4 5]
 [1 0 3 6 5]]


In [23]:
print("rowsum is :\n",np.sum(c,axis=1))
print("colsum is :\n",np.sum(np.sum(c,axis=0)))

rowsum is :
 [[15]
 [15]]
colsum is :
 30


In [24]:
print(np.diag(np.arange(0,6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [25]:
print("sum is :",np.sum(c))

sum is : 30


In [27]:
np.savetxt('array.txt',c)

In [32]:
d=np.loadtxt('array.txt').astype(int)
print(type(d))
print(d)

<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [1 0 3 6 5]]


In [34]:
arr1=np.arange(0,5)
arr2=np.arange(2,7)
print(arr1,arr2)

[0 1 2 3 4] [2 3 4 5 6]


In [36]:
print(np.array_equal(arr1,arr2))

False


In [37]:
arr4=np.random.rand(4,4)
print(arr4)

[[0.35565061 0.2620358  0.8723711  0.1136114 ]
 [0.34986109 0.88861012 0.3226765  0.46199229]
 [0.31771258 0.12401975 0.61970564 0.64488023]
 [0.67112101 0.19104727 0.4705164  0.12938521]]


In [41]:
arr4[[0,3]]=arr4[[3,0]]
print(arr4)

[[0.67112101 0.19104727 0.4705164  0.12938521]
 [0.34986109 0.88861012 0.3226765  0.46199229]
 [0.31771258 0.12401975 0.61970564 0.64488023]
 [0.35565061 0.2620358  0.8723711  0.67112101]]


In [42]:
print(arr1*arr2)

[ 0  3  8 15 24]
